### ISSUE TITLE
Put input size limit

### ISSUE THREAD

**Issue by RaSan147** [RaSan147/VoiceAI-Asuna#16]
Block from both js and py

**Comment by coolst3r** [comment]
just drop input dont log it can be used as ddos method

**Comment by RaSan147** [comment]
> just drop input dont log it can be used as ddos method

Please explain a bit more

**Comment by RaSan147** [comment]
I must save user inputs (because of training data collection)
But i may he able to limit how much data can be sent (if more than that, will close the connection)

**Comment by coolst3r** [comment]
or like cooldown like 1 or 2 seconds delay so it wont flood you

**Comment by RaSan147** [comment]
> you can also make so you wait till she replied then send

That'd be a issue also actually won't do a thing, ddos attack will use send data regardless of response and js. And server must take care of each of them otherwise won't be able to handle heavy user load either

**Comment by RaSan147** [comment]
If we block based on user, we'll still need to receive that message. Imagine getting millions per second just to check that they are not even from a valid user

**Comment by coolst3r** [comment]
you can flood it with replys using automation

**Comment by RaSan147** [comment]
I'll try

**Comment by RaSan147** [comment]
Done
