### ISSUE TITLE
[Bug] blank signup/login form are being accepted 

### ISSUE THREAD

**Issue by RaSan147** [RaSan147/VoiceAI-Asuna#17]
Check both js and py

**Comment by coolst3r** [comment]
yeah but does not matter if it is accepted what matter is if a you can inject code

**Comment by RaSan147** [comment]
> yeah but does not matter if it is accepted what matter is if a you can inject code

I don't understand what you've ment, but I'm using  python in backend and not even touching the username (oh shit thats a issue) but i don't think code injection will work on me (not using sql or any traditional database)

**Comment by RaSan147** [comment]
Oh got it, yeah making (right now) server side changes to slap on the injected code

Thanks (really need a guy like you)

**Comment by coolst3r** [comment]
no mean someone can fuzz input and find a way to inject code

**Comment by RaSan147** [comment]
Try me 😄 (if you know what to do). Lets see the server burn

**Comment by RaSan147** [comment]
Just don't databomb it (I don't have unlimited storage lol)

**Comment by coolst3r** [comment]
> Try me smile (if you know what to do). Lets see the server burn

that would delete everything so no or have alot of unwanted affects

**Comment by RaSan147** [comment]
Try that on you vm (the one you let me use) and report
