### ISSUE TITLE
How to display the whole body of the model

### ISSUE THREAD

**Issue by kirbystudy** [RaSan147/VoiceAI-Asuna#19]

**Comment by RaSan147** [comment]
If you are on pc, just change browser window size (no zoom in zoom out button sorry, api issue)
On mobile, again sorry.
If you're expecting to see feet, big sorry. Live2D feet animation is really hard. So it's not implemented 😅

**Comment by kirbystudy** [comment]
Thank you for your answer. I have another question, can the clarity of the model be adjusted?

**Comment by RaSan147** [comment]
> Thank you for your answer. I have another question, can the clarity of the model be adjusted?

I'm using about 1080p sizable images. But often scaling makes it blurry (not alway)

**Comment by kirbystudy** [comment]
Yes, scaling the model will blur. Can this solve the problem?
![image](https://user-images.githubusercontent.com/63231787/232996398-53f4b88a-18fa-4adf-99a1-7026bce9d2f0.png)

**Comment by RaSan147** [comment]
nah, its a bit issue in the web rendering, nothing can be done from my end (unless i find some nasty issue deep down in the js package)

**Comment by kirbystudy** [comment]
ok, thank you for your answer.

**Comment by RaSan147** [comment]
> I hope future versions will address this issue

did you try on different browsers. also could you kindly please send a screenshot

**Comment by kirbystudy** [comment]
![image](https://user-images.githubusercontent.com/63231787/233123502-b785f522-f802-472b-8e50-17b14010891a.png)
On the left is Egde browser, and on the right is Google browser, both with the same clarity.

**Comment by RaSan147** [comment]
Well there's no hope then 😥
As you can see here
https://github.com/RaSan147/voiceAI-skins/tree/main/asuna/asuna_01/moc/asuna_01.1024

All the pic are quite HD, but smaller window or scale down causes the blurriness 😥

**Comment by RaSan147** [comment]
@kirbystudy what tool are you using... :D 

oh checked your repo, if it was in english i might try helping you.
Also, just interested, did you manage to find a way to center align the character??

**Comment by kirbystudy** [comment]
> @kirbystudy what tool are you using... :D
> 
> oh checked your repo, if it was in english i might try helping you. Also, just interested, did you manage to find a way to center align the character??

I don't understand what you are saying. Could you be more specific.

**Comment by RaSan147** [comment]
i asked what tool are you using to visualize the live2d model
also asked if you found any way to keep the live2d model at the center of the browser window

**Comment by kirbystudy** [comment]
I don't know what tools to use for visualization, the live2d model was found in the Github repository.
My idea is to adjust the x-axis and y-axis positions of the live2d model.
