### ISSUE TITLE
Skins missing?

### ISSUE THREAD

**Issue by RaSan147** [RaSan147/VoiceAI-Asuna#7]
![Screenshot_2023-02-10-22-04-50-45_c759c44d10a956b96f85cc66750ff86e](https://user-images.githubusercontent.com/34002411/218138939-3c7146a8-3630-4201-ab71-d1e61a5a1bf3.jpg)

**Comment by RaSan147** [comment]
fixed it

**Comment by mangoldipsaha** [comment]
bro how to run this project and also config
sahamangoldip@gmail.com
from India

**Comment by RaSan147** [comment]
@mangoldipsaha Read the homepage readme...
You got python installed right? Well on mobile you'll need pydroid (free version will work too). If you have any trouble, make a new issue and tell me the details
